version: '3'
services:
    jupyterlab:
        build: .
        ports:
          - "8888:8888"
        environment:
          - BONMIN_VERSION=1.8.7
          - COUENNE_VERSION=0.5.7
          - IPOPT_VERSION=3.12.12
          - SCIP_VERSION=6.0.1
        volumes:
          - ./workdir:/root
